# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Voxel Adventures
tagline:          'Development blog'
description:      'Personal development blog where I share my knowledge about CUDA and Voxel rendering'
url:              https://voxel-tracer.github.io
baseurl:          https://voxel-tracer.github.io

author:
  name:           'Voxel Tracer'
  url:            https://twitter.com/voxel-tracer

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/voxel-tracer/

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
